version: '3.9'

services:
  server:
    build: .
    ports:
      - 8081:8081
    command: "npm run start"
    volumes:
      - .:/app/
  

  postgres-compose:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: easysell
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"
    networks:
      - network
  
    
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
    ports:
      - 15432:80
    depends_on:
      - postgres-compose
    networks:
      - network
  

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true