version: '3.9'

services:
  
  server:
    image: node:latest
    container_name: server
    env_file:
      - .env
    depends_on:
      - postgres-compose
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    command: bash -c "npx prisma generate && npm start "
  

  postgres-compose:
    image: phdcoder/postgresbr
    restart: always
    container_name: postgres-compose
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: easysell
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"
    networks:
      - network
  
    
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
    ports:
      - 15432:80
    depends_on:
      - postgres-compose
    networks:
      - network
  

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true